# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: R
r: bioc-devel
sudo: false
warnings_are_errors: true

# BiocCheck
bioc_packages:
  - BiocCheck

after_success:
  - R CMD BiocCheck --new-package --no-check-vignettes [deconvR]*.tar.gz
