context("deconvolution")
library(deconvR)

test_that("deconvolute nnls", {
  ref_atlas = readRDS(system.file("reference_atlas_nodup.RDS", package = "deconvR"))
  simulation = simulateCellMix(5)
  bulkTable = simulation[[1]]
  proportionsTable = simulation[[2]]
  expect_equal(dim(deconvolute(bulk=bulkTable)), c(5,length(colnames(ref_atlas[,-1]))))
  expect_equal(dim(deconvolute(bulk=bulkTable[-1,])), c(5,length(colnames(ref_atlas[,-1]))))
  expect_equal(colnames(deconvolute(bulk=bulkTable)), colnames(ref_atlas[,-1]))
  expect_equivalent(sapply(deconvolute(bulk=bulkTable)[,], typeof), rep_len("double", length(colnames(ref_atlas[,-1]))))
  expect_equal(sum(deconvolute(bulk=bulkTable)[1,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable)[2,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable)[3,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable)[4,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable)[5,]), 1)
  expect_error(deconvolute())
  expect_error(deconvolute(bulk=bulkTable, model="n"))
  expect_error(deconvolute(bulk=bulkTable[,-1], model="nnls"))
  expect_error(deconvolute(model="nnls"))
  expect_output(deconvolute(bulk=bulkTable), "DECONVOLUTION WITH NNLS")
  expect_output(deconvolute(bulk=bulkTable), "SUMMARY OF RMSE VALUES USING  NNLS")
  expect_equal(dim(deconvolute(bulk=bulkTable, model="nnls")), dim(proportionsTable))
  expect_equal(colnames(deconvolute(bulk=bulkTable, model="nnls")), colnames(ref_atlas[,-1]))
})

test_that("deconvolute svr", {
  ref_atlas = readRDS(system.file("reference_atlas_nodup.RDS", package = "deconvR"))
  simulation = simulateCellMix(5)
  bulkTable = simulation[[1]]
  proportionsTable = simulation[[2]]
  expect_equal(dim(deconvolute(bulk=bulkTable, model="svr")), c(5,length(colnames(ref_atlas[,-1]))))
  expect_equal(dim(deconvolute(bulk=bulkTable[-1,], model="svr")), c(5,length(colnames(ref_atlas[,-1]))))
  expect_equal(colnames(deconvolute(bulk=bulkTable, model="svr")), colnames(ref_atlas[,-1]))
  expect_equivalent(sapply(deconvolute(bulk=bulkTable, model="svr")[,], typeof), rep_len("double", length(colnames(ref_atlas[,-1]))))
  expect_equal(sum(deconvolute(bulk=bulkTable, model="svr")[2,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="svr")[3,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="svr")[4,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="svr")[5,]), 1)
  expect_error(deconvolute(bulk=bulkTable[,-1], model="svr"))
  expect_error(deconvolute(model="svr"))
  expect_output(deconvolute(bulk=bulkTable, model="svr"), "DECONVOLUTION WITH SVR")
  expect_output(deconvolute(bulk=bulkTable, model="svr"), "SUMMARY OF RMSE VALUES USING  SVR")
  expect_equal(dim(deconvolute(bulk=bulkTable, model="svr")), dim(proportionsTable))
  expect_equal(colnames(deconvolute(bulk=bulkTable, model="svr")), colnames(ref_atlas[,-1]))
})

test_that("deconvolute qp", {
  ref_atlas = readRDS(system.file("reference_atlas_nodup.RDS", package = "deconvR"))
  simulation = simulateCellMix(5)
  bulkTable = simulation[[1]]
  proportionsTable = simulation[[2]]
  expect_equal(dim(deconvolute(bulk=bulkTable, model="qp")), c(5,length(colnames(ref_atlas[,-1]))))
  expect_equal(dim(deconvolute(bulk=bulkTable[-1,], model="qp")), c(5,length(colnames(ref_atlas[,-1]))))
  expect_equal(colnames(deconvolute(bulk=bulkTable, model="qp")), colnames(ref_atlas[,-1]))
  expect_equivalent(sapply(deconvolute(bulk=bulkTable, model="qp")[,], typeof), rep_len("double", length(colnames(ref_atlas[,-1]))))
  expect_equal(sum(deconvolute(bulk=bulkTable, model="qp")[1,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="qp")[2,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="qp")[3,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="qp")[4,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="qp")[5,]), 1)
  expect_error(deconvolute(bulk=bulkTable[,-1], model="qp"))
  expect_error(deconvolute(model="qp"))
  expect_output(deconvolute(bulk=bulkTable, model="qp"), "DECONVOLUTION WITH QP")
  expect_output(deconvolute(bulk=bulkTable, model="qp"), "SUMMARY OF RMSE VALUES USING  QP")
  expect_equal(dim(deconvolute(bulk=bulkTable, model="qp")), dim(proportionsTable))
  expect_equal(colnames(deconvolute(bulk=bulkTable, model="qp")), colnames(ref_atlas[,-1]))
})

test_that("deconvolute rlm", {
  ref_atlas = readRDS(system.file("reference_atlas_nodup.RDS", package = "deconvR"))
  simulation = simulateCellMix(5)
  bulkTable = simulation[[1]]
  proportionsTable = simulation[[2]]
  expect_equal(dim(deconvolute(bulk=bulkTable, model="rlm")), c(5,length(colnames(ref_atlas[,-1]))))
  expect_equal(dim(deconvolute(bulk=bulkTable[-1,], model="rlm")), c(5,length(colnames(ref_atlas[,-1]))))
  expect_equal(colnames(deconvolute(bulk=bulkTable, model="rlm")), colnames(ref_atlas[,-1]))
  expect_equivalent(sapply(deconvolute(bulk=bulkTable, model="rlm")[,], typeof), rep_len("double", length(colnames(ref_atlas[,-1]))))
  expect_equal(sum(deconvolute(bulk=bulkTable, model="rlm")[1,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="rlm")[2,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="rlm")[3,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="rlm")[4,]), 1)
  expect_equal(sum(deconvolute(bulk=bulkTable, model="rlm")[5,]), 1)
  expect_error(deconvolute(bulk=bulkTable[,-1], model="rlm"))
  expect_error(deconvolute(model="rlm"))
  expect_output(deconvolute(bulk=bulkTable, model="rlm"), "DECONVOLUTION WITH RLM")
  expect_output(deconvolute(bulk=bulkTable, model="rlm"), "SUMMARY OF RMSE VALUES USING  RLM")
  expect_equal(dim(deconvolute(bulk=bulkTable, model="rlm")), dim(proportionsTable))
  expect_equal(colnames(deconvolute(bulk=bulkTable, model="rlm")), colnames(ref_atlas[,-1]))
})
